
PROC SORT DATA=INPUT;
	BY SUBJECT ONCOLOGIST REPEAT;
RUN;

PROC MEANS DATA=INPUT NOPRINT;
	VAR VOLUME;
	BY SUBJECT ONCOLOGIST;
	OUTPUT OUT=MEANS MEAN=VOLUME;
RUN;

DATA MEANS;
	SET MEANS;
	REPEAT=ONCOLOGIST;
RUN;

PROC MIXED DATA=MEANS METHOD=TYPE3;
	CLASS SUBJECT ONCOLOGIST;
	MODEL VOLUME = ONCOLOGIST /SOLUTION CL OUTP=PRED2;
	RANDOM SUBJECT;
RUN;

PROC UNIVARIATE DATA=PRED2 NORMAL;
	VAR RESID;
	PROBPLOT RESID /NORMAL(MU=est SIGMA=est);
RUN;

PROC GLM DATA=PRED2;
	CLASS ONCOLOGIST;
	MODEL RESID = ONCOLOGIST;
	MEANS ONCOLOGIST/ HOVTEST=Bartlett;
RUN;


PROC SORT DATA=MEANS;
	BY SUBJECT;
RUN;

PROC MIXED DATA=MEANS METHOD=TYPE3;
	CLASS SUBJECT ONCOLOGIST;
	MODEL VOLUME = ONCOLOGIST /SOLUTION CL OUTP=PRED1;
RUN;

PROC UNIVARIATE DATA=PRED1 NORMAL;
	VAR RESID;
	PROBPLOT RESID /NORMAL(MU=est SIGMA=est);
RUN;

PROC GLM DATA=PRED1;
	CLASS ONCOLOGIST;
	MODEL RESID = ONCOLOGIST;
	MEANS ONCOLOGIST/ HOVTEST=Bartlett;
RUN;

PROC MIXED DATA=MEANS METHOD=TYPE3 COVTEST CL;
	CLASS SUBJECT ONCOLOGIST;
	MODEL VOLUME= ONCOLOGIST/SOLUTION DDFM=SAT CL;
	RANDOM SUBJECT/SOLUTION;
	LSMEANS ONCOLOGIST /CL;
RUN;


PROC MIXED DATA=ANOVA METHOD=TYPE3;
	CLASS F1 … Fk R1 … Rk;
	MODEL Y =  F1 F2 … Fk /SOLUTION DDFM=SAT CL;
	RANDOM R1 R2 … Rk /SOLUTION;
	LSMEANS F1 /CL;
RUN;


*W6-2;
DATA RCT;
 SET SAS.Cellsaver;
 WHERE TIME=3;
RUN;

PROC MIXED DATA=RCT METHOD=TYPE3;
	CLASS TRT;
	MODEL RESP = TRT/SOLUTION CL;
	LSMEANS TRT/DIFF;
RUN;

PROC MIXED DATA=RCT METHOD=TYPE3;
	CLASS TRT;
	MODEL RESP = TRT/SOLUTION;
	LSMEANS TRT/DIFF ADJUST=BON;
RUN;

PROC MIXED DATA=RCT METHOD=TYPE3;
	CLASS TRT;
	MODEL RESP = TRT/SOLUTION;
	LSMEANS TRT/DIFF=CONTROL('0') ADJUST=BON;
RUN;


DATA RCTG;
 SET RCT;
 WHERE CENTER=1;
 RESPL=LOG(RESP);
 KEEP ID RESPL;
RUN;

DATA OUTLIER;
ID=999;
RESPL=2.5;
run;

DATA RCTG;
 SET RCTG OUTLIER;
RUN;

PROC UNIVARIATE DATA=RCTG;
Histogram RESPL /normal;
run;

proc means data=RCTG mean std n;
	var RESPL ;
	output out=L10_sumstat mean=mean median=median std=std n=n;
run;

data RCTG;
set RCTG;
if _n_=1 then set L10_sumstat;
drop _TYPE_ _FREQ_;
run;

DATA Grubbs;
	SET RCTG;
	U = (Y-MEAN)/STD;
	Grubbs=ABS(U);
	*Adapt C_exact manually for different N;
	C_onesided_exact= 2.56;
	C_twosided_exact= 2.71;	
	t = quantile("t", 0.05 / (2*N), N-2);
	C_twosided_approx = (n-1) * sqrt(t**2 / (n * (t**2 + n - 2)));
	u_inv = u*sqrt((n-2)) / sqrt(n-1-u**2);
	p_twosided_approx = min(2*n*MIN(1-cdf("t", u_inv, n-2),cdf("t", u_inv, n-2)), 1);
RUN;

PROC SORT DATA =Grubbs;
	BY descending Grubbs;
RUN;


DATA RCTG;
 SET RCT;
 WHERE CENTER=1;
RUN;

%grubbs(RCTG,RESP,ID);


/*TUKEY */ 
PROC MIXED DATA=RCT METHOD=TYPE3;
	CLASS TRT;
	MODEL RESP = TRT/SOLUTION;
	LSMEANS TRT/DIFF=CONTROL ADJUST=TUKEY CL;
RUN;

PROC MIXED DATA=RCT METHOD=TYPE3;
	CLASS TRT;
	MODEL RESP = TRT/SOLUTION;
	LSMEANS TRT/DIFF ADJUST=SCHEFFE CL;
RUN;

PROC GLM DATA=ANOVA;
	CLASS TRT;
	MODEL RESP = TRT;
	MEANS TRT/DUNCAN;
RUN;

PROC MIXED DATA=RCT METHOD=TYPE3;
	CLASS TRT;
	MODEL RESP = TRT/SOLUTION;
	LSMEANS TRT/DIFF=CONTROL('0') ADJUST=TUKEY;
RUN;

PROC MIXED DATA=RCT METHOD=TYPE3;
	CLASS TRT;
	MODEL RESP = TRT/SOLUTION;
	LSMEANS TRT / DIFF ADJUST=DUNNETT CL;
RUN;
